name: "MagicMirror² (master) and MMM-Pir build Testing"

on: [pull_request]

jobs:
  build:
    name: Test install MMM-Pir
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.14.0, 22.x, 23.x]
        mm-version: [v2.28.0, v2.31.0, master]
    steps:
      - name: "Use Node.js ${{ matrix.node-version }} and MM ${{ matrix.mm-version }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Checkout MagicMirror²
        uses: actions/checkout@v4
        with:
          repository: MagicMirrorOrg/MagicMirror
          ref: ${{ matrix.mm-version }}

      - name: Install MagicMirror²
        run: npm install

      - name: Checkout MMM-Pir
        uses: actions/checkout@v4
        with:
          path: MagicMirror/modules/MMM-Pir

      - name: Install MMM-Pir
        run: npm install
        working-directory: MagicMirror/modules/MMM-Pir
        continue-on-error: false
